### ISSUE TITLE
没有返回结果

### ISSUE THREAD

**Issue by K0uaz** [FishM4n/Fofa-collect#1]
![image](https://user-images.githubusercontent.com/32475005/113310430-ce180900-933a-11eb-80b6-fd8deadbcdc8.png)
点击查询无任何反应，在Config.ini写入email，打开.jar后email一栏里会产生奇怪的中文字符
![image](https://user-images.githubusercontent.com/32475005/113310527-eb4cd780-933a-11eb-87b1-3b2dd641b79b.png)

**Comment by bwcxljsm** [comment]
查询不到 可能是今天fofa炸了的原因
乱码可能是编码有问题,换个文本编辑器试试，utf8格式
我这测试一切正常
![GIF](https://user-images.githubusercontent.com/59049655/113324619-e7748180-9349-11eb-942d-5cc0d3e87d17.gif)

**Comment by bwcxljsm** [comment]
如果还不行，请加我微信
