### ISSUE TITLE
1.8版本好像使用的时候有bug

### ISSUE THREAD

**Issue by 0730Nophone** [FishM4n/Fofa-collect#11]
1.8版本好像使用的时候有bug， 查询500条爆出未查询到数据 但是在fofa web上显示有525条

**Comment by bwcxljsm** [comment]
fofa还在试运行，有点问题是正常的。
<img width="210" alt="bwcx_2022-02-16_08-51-54" src="https://user-images.githubusercontent.com/59049655/154175273-93c8974d-88ac-4d99-8c00-cae931ca09aa.png">

**Comment by bwcxljsm** [comment]
不是工具问题
