### ISSUE TITLE
查询条数大于1001条就报“未查询到数据”的BUG

### ISSUE THREAD

**Issue by 0rzNuII** [FishM4n/Fofa-collect#12]
这是50条，正常回显：
![image](https://user-images.githubusercontent.com/40875899/155082555-9bfa4639-a18c-4d62-9e7e-871f092f0213.png)

这是100条，正常回显：
![image](https://user-images.githubusercontent.com/40875899/155082587-9868abc6-e4fc-4fc7-af31-e222af24b89e.png)

这是500条，开始报错：
![image](https://user-images.githubusercontent.com/40875899/155082495-cafcfb82-c940-495c-9d33-ce70a5ac2673.png)

**Comment by bwcxljsm** [comment]
控制台会输出api查询地址，请复制到浏览器访问查看是否为fofa查询失败导致
并非工具问题
具体请咨询fofa
![bwcx_2022-02-22_15-31-59](https://user-images.githubusercontent.com/59049655/155083943-488cfd0f-d095-4c41-9a17-d206195bb58f.png)
![bwcx_2022-02-22_15-34-08](https://user-images.githubusercontent.com/59049655/155084098-891bffc8-3526-4240-b4a0-e7ab79bccf94.png)

**Comment by 0rzNuII** [comment]
> 控制台会输出api查询地址，请复制到浏览器访问查看是否为fofa查询失败导致 并非工具问题 具体请咨询fofa ![bwcx_2022-02-22_15-31-59](https://user-images.githubusercontent.com/59049655/155083943-488cfd0f-d095-4c41-9a17-d206195bb58f.png) ![bwcx_2022-02-22_15-34-08](https://user-images.githubusercontent.com/59049655/155084098-891bffc8-3526-4240-b4a0-e7ab79bccf94.png)

哦哦哦，好的，谢谢
