### ISSUE TITLE
导出csv有问题

### ISSUE THREAD

**Issue by LittleYell0wMan** [FishM4n/Fofa-collect#3]
勾选了排除干扰和全部数据，导出csv里的domain里会出现HTTP头

**Comment by bwcxljsm** [comment]
domain fofa默认有的就带http头，，你可以用ip列不带，或者分列删除就行了

**Comment by LittleYell0wMan** [comment]
大佬，后续有没有添加只导出ip+端口的功能呢

**Comment by bwcxljsm** [comment]
不考虑，excel能解决
