### ISSUE TITLE
建议导出结果增加Host列放域名，原域名列改为http和https

### ISSUE THREAD

**Issue by sv3nbeast** [FishM4n/Fofa-collect#5]
fofa的查询结果是如果是https协议，他会给https://www.baidu.com, http协议不会加http前缀，所以建议直接代码里加上不是https协议的就http://+域名，这种的为一列

然后加一列host放没有http://和https://的域名，相等于查询结果replace掉https://

主要是为了满足一些工具需要传入http或https前缀，一些工具只需要传入域名的场景

感谢分享的fofa工具~

**Comment by bwcxljsm** [comment]
增加了http://      需要没有http://的直接excel分列一下就行  增加一列显得臃肿
